
package wscalc.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsCalcImpl", targetNamespace = "http://ws.WsCalc")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsCalcImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.WsCalc", className = "wscalc.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.WsCalc", className = "wscalc.ws.AddResponse")
    @Action(input = "http://ws.WsCalc/WsCalcImpl/addRequest", output = "http://ws.WsCalc/WsCalcImpl/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://ws.WsCalc", className = "wscalc.ws.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://ws.WsCalc", className = "wscalc.ws.SubResponse")
    @Action(input = "http://ws.WsCalc/WsCalcImpl/subRequest", output = "http://ws.WsCalc/WsCalcImpl/subResponse")
    public double sub(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://ws.WsCalc", className = "wscalc.ws.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://ws.WsCalc", className = "wscalc.ws.MulResponse")
    @Action(input = "http://ws.WsCalc/WsCalcImpl/mulRequest", output = "http://ws.WsCalc/WsCalcImpl/mulResponse")
    public double mul(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://ws.WsCalc", className = "wscalc.ws.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://ws.WsCalc", className = "wscalc.ws.DivResponse")
    @Action(input = "http://ws.WsCalc/WsCalcImpl/divRequest", output = "http://ws.WsCalc/WsCalcImpl/divResponse")
    public double div(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
