
package wscalc.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsCalcImplService", targetNamespace = "http://ws.WsCalc", wsdlLocation = "http://192.168.43.76:8181/ws/wscalc?wsdl")
public class WsCalcImplService
    extends Service
{

    private final static URL WSCALCIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCALCIMPLSERVICE_EXCEPTION;
    private final static QName WSCALCIMPLSERVICE_QNAME = new QName("http://ws.WsCalc", "WsCalcImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.43.76:8181/ws/wscalc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCALCIMPLSERVICE_WSDL_LOCATION = url;
        WSCALCIMPLSERVICE_EXCEPTION = e;
    }

    public WsCalcImplService() {
        super(__getWsdlLocation(), WSCALCIMPLSERVICE_QNAME);
    }

    public WsCalcImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCALCIMPLSERVICE_QNAME, features);
    }

    public WsCalcImplService(URL wsdlLocation) {
        super(wsdlLocation, WSCALCIMPLSERVICE_QNAME);
    }

    public WsCalcImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCALCIMPLSERVICE_QNAME, features);
    }

    public WsCalcImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCalcImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsCalcImpl
     */
    @WebEndpoint(name = "WsCalcImplPort")
    public WsCalcImpl getWsCalcImplPort() {
        return super.getPort(new QName("http://ws.WsCalc", "WsCalcImplPort"), WsCalcImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsCalcImpl
     */
    @WebEndpoint(name = "WsCalcImplPort")
    public WsCalcImpl getWsCalcImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.WsCalc", "WsCalcImplPort"), WsCalcImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCALCIMPLSERVICE_EXCEPTION!= null) {
            throw WSCALCIMPLSERVICE_EXCEPTION;
        }
        return WSCALCIMPLSERVICE_WSDL_LOCATION;
    }

}
